# Homework 01
---
[mlbookcamp 01-intro](https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/homework.md)

## Question 1
What's the version of NumPy that you installed?

In [1]:
import numpy as np
np.__version__

'1.22.3'

## Question 2
What's the version of Pandas?

In [2]:
import pandas as pd
pd.__version__

'1.3.3'

## Question 3
What's the average price of BMW cars in the dataset?

In [3]:
import os.path as osp

DIRPATH="./data/"
FILENAME = "car-prices.csv"
DATAPATH = osp.join(DIRPATH, FILENAME)

### Downloading data

In [4]:
! ./downloading_data.sh -d $DIRPATH -f $FILENAME https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-30 14:49:18--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolvendo raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8002::154, ...
Conectando-se a raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 1475504 (1,4M) [text/plain]
Salvando em: “./data//car-prices.csv”

./data//car-prices. 100%[===================>]   1,41M  4,98MB/s    em 0,3s    

2022-09-30 14:49:19 (4,98 MB/s) - “./data//car-prices.csv” salvo [1475504/1475504]



### Resolution

In [5]:
data = pd.read_csv(DATAPATH)
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [72]:
data.loc[data['Make'] == 'BMW', 'MSRP'].mean()

61546.76347305389

## Question 4
Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [13]:
data.loc[data['Year'] >= 2015, 'Engine HP'].isna().sum()

51

## Question 5
- Calculate the average "Engine HP" in the dataset.
- Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
- Now, calcualte the average of "Engine HP" again.
- Has it changed?

In [16]:
previous_mean = data['Engine HP'].mean()
previous_mean

249.38607007176023

In [17]:
new_mean = data['Engine HP'].fillna(previous_mean).mean()
new_mean

249.38607007176023

## Question 6
- Select all the "Rolls-Royce" cars from the dataset.
- Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
- Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time




In [24]:
X = data.loc[data['Make'] == 'Rolls-Royce', ['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates().to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [35]:
XTX = X.T @ X
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [63]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv.sum()

0.032212320677486125

## Questions 7
- Create an array y with values `[1000, 1100, 900, 1200, 1000, 850, 1300]`.
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the first element of w?.
> Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [64]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [66]:
w =  XTX_inv @ X.T @ y
w[0]

0.19989598183188978